/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_calloc.c                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: nireher <nireher-@student.42madrid.com>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/11/23 05:10:09 by nireher           #+#    #+#             */
/*   Updated: 2023/11/23 06:53:46 by nireher-         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libft.h"

/*
 * Clear-allocation, just like the name says, cleans the garbage mem
 * generated by malloc by initializing the dinamic block mem to 0
 */

void	*ft_calloc(size_t num, size_t num_size)
{
	const size_t	total_len = num * num_size;
	void			*buffer;

	if (!num || !num_size)
		return (malloc(0));
	buffer = (void *)malloc(total_len);
	if (!buffer)
		return (NULL);
	ft_bzero(buffer, total_len);
	return (buffer);
}
